name: Pull request test workflow

on:
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    name: Building

    runs-on: ubuntu-latest

    steps:
      - name: Hello Y
          uses: actions/hello-world-javascript-action@v1
          with:
            who-to-greet: 'Y'
          id: hello

      - name: Echo the greeting's time
          run: echo 'The time was ${{ steps.hello.outputs.time }}.'